### ISSUE TITLE
Pyvenv Recommendation

### ISSUE THREAD

**Issue by pjhampton** [PythonProgramming/Support-Vector-Machines---Basics-and-Fundamental-Investing-Project#1]
Should we not be recommending the use of a Virtual Environment such as PyVenv (Python 3) or VirtualEnv (Python 2)? This will keep the dependencies required by different projects in separate places, by creating virtual Python environments for them.

For example, downloading this project and running `pip install -r requirements.txt` will install six v1.9.0, but the user may have a project that requires six v0.9 (for hypothetical example). This would mess up the backwards compatibility. 

I propose the process should be:
#### Mac OSx & Linux

```
pyvenv venv && cd venv
source bin/activate
git clone https://github.com/PythonProgramming/Support-Vector-Machines---Basics-and-Fundamental-Investing-Project.git
cd Support-Vector-Machines---Basics-and-Fundamental-Investing-Project
pip install -r requirements.txt
```
#### Windows

```
pyvenv venv && cd venv
Scripts\activate
git clone https://github.com/PythonProgramming/Support-Vector-Machines---Basics-and-Fundamental-Investing-Project.git
cd Support-Vector-Machines---Basics-and-Fundamental-Investing-Project
pip install -r requirements.txt
```

Further, PaaS such as Heroku recommend deploying the likes of django in a virtualenv - this, in essence should make it easier to deploy: https://devcenter.heroku.com/articles/getting-started-with-django

What do you think?

**Comment by Sentdex** [comment]
Sorry for my delay, came down with a cold, still dying over here! 

If you think that would be useful, then sure. I've never personally used virtual environments except for web development, though, as you noted, the django series wasn't a venv either. The Flask tutorials use a venv. I see the use of them for version control, just not a typical user of them myself.

I am also a github noob, so I am not sure what's required to let people make use of requirements.txt, of if people generally expect a virtual environment. If venv is what people tend to expect, then let's go ahead and include that. People can still view the source if they want, or they can use github as it was meant to be used. 

I'll go with your best judgement here.
